sudo: false

services:
   - mongodb
   - redis-server
   - elasticsearch
#   - couchdb

language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"

branches:
  only:
    - master
    - elasticsearch

notifications:
  email:
    - adriano@raiano.ch
