# before_script: "npm install"

services:
   - mongodb
   - redis-server
#   - couchdb

language: node_js
node_js:
  - 0.8
  - 0.10

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch